config/routes.rb
Padb::Application.routes.draw do
  resources :departments

  resources :incidents do
    get :autocomplete_department_name, :on => :collection
  end
  root "pages#home"
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"

  get "posts", to: "pages#posts", as: "posts"
  get "posts/:id", to: "pages#show_post", as: "post"
  devise_for :users

  namespace :admin do
    root "base#index"
    resources :users
    get "posts/drafts", to: "posts#drafts", as: "posts_drafts"
    get "posts/dashboard", to: "posts#dashboard", as: "posts_dashboard"
    resources :posts
  end

end

app/models/incident.rb
# == Schema Information
#
# Table name: incidents
#
#  id                              :integer          not null, primary key
#  summary                         :text
#  year                            :integer
#  month                           :string
#  city                            :string
#  state                           :string
#  context                         :string
#  abuse_force                     :boolean
#  abuse_search                    :boolean
#  abuse_misconduct                :boolean
#  abuse_intimidation              :boolean
#  abuse_sexual                    :boolean
#  abuse_escalation                :boolean
#  abuse_animal                    :boolean
#  force_variety                   :string
#  search_variety                  :string
#  misconduct_variety              :string
#  intimidation_variety            :string
#  sexual_variety                  :string
#  escalation_variety              :string
#  victim_count                    :integer
#  victim_notes                    :text
#  victim_race                     :string
#  victim_age                      :string
#  victim_gender                   :string
#  officer_count                   :integer
#  officer_race                    :string
#  officer_tenure                  :string
#  officer_gender                  :string
#  outcome_physical_variety        :string
#  outcome_legal_variety           :string
#  outcome_hr_variety              :string
#  outcome_internal_variety        :string
#  outcome_dept_statement_variety  :string
#  outcome_union_statement_variety :string
#  outcome_dollars                 :integer
#  created_at                      :datetime         not null
#  updated_at                      :datetime         not null
#  department_id                   :integer
#  abuse_retrained                 :boolean
#

require 'elasticsearch/model'
class Incident < ActiveRecord::Base

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  # http://pivotallabs.com/rspec-elasticsearchruby-elasticsearchmodel/
  # index_name [Rails.env, model_name.collection.gsub(/\//, '-')].join('_')

  validates :summary, :year, :state, :context, presence: true
  belongs_to :department
  accepts_nested_attributes_for :department

  serialize :force_variety
  serialize :search_variety
  serialize :misconduct_variety
  serialize :intimidation_variety
  serialize :sexual_variety
  serialize :escalation_variety
  serialize :victim_race
  serialize :victim_age
  serialize :victim_gender
  serialize :officer_race
  serialize :officer_tenure
  serialize :officer_gender
  serialize :outcome_physical_variety
  serialize :outcome_legal_variety
  serialize :outcome_hr_variety
  serialize :outcome_internal_variety
  serialize :outcome_dept_statement_variety
  serialize :outcome_union_statement_variety
  serialize :urls
end

app/models/incident_form.rb
class IncidentForm
  include ActiveModel::Model

  attr_accessor :summary, :year, :month, :city, :state, :context,
    :force_variety, :search_variety, :misconduct_variety, :intimidation_variety,
    :sexual_variety, :escalation_variety, :victim_count, :victim_race, :victim_age,
    :victim_gender, :victim_notes, :officer_count, :officer_race, :officer_tenure,
    :officer_gender, :department_name, :department_city, :department_state,
    :department_level, :department_notes, :outcome_dollars, :outcome_hr_variety,
    :outcome_legal_variety, :outcome_physical_variety, :outcome_internal_variety,
    :outcome_dept_statement_variety, :outcome_union_statement_variety,
    :abuse_animal, :department_county, :abuse_restrained, :urls

  validates :summary, :year, :state, :context,
    :department_name, :department_city, :department_state, presence: true
  validates :year, numericality: { only_integer: true, greater_than: 2005 }

  def save
    if valid?
      persist!
    else
      false
    end
  end

  private
  def persist!
    dept = Department.where(name: department_name,
      city: department_city, state: department_state).first_or_create
    dept.level = department_level
    dept.notes = department_notes
    dept.county = department_county
    puts dept.level
    dept.save

    dept.incidents.create!(summary: summary, year: year, month: month,
      city:city, state: state, context: context, force_variety: force_variety,
      search_variety: search_variety, misconduct_variety: misconduct_variety,
      intimidation_variety: intimidation_variety, sexual_variety: sexual_variety,
      escalation_variety: escalation_variety, victim_count: victim_count,
      victim_age: victim_age, victim_race: victim_race, victim_gender: victim_gender,
      officer_count: officer_count, officer_race: officer_race,
      officer_tenure: officer_tenure, officer_gender: officer_gender,
      outcome_dollars: outcome_dollars, outcome_hr_variety: outcome_hr_variety,
      outcome_legal_variety: outcome_legal_variety, outcome_physical_variety: outcome_physical_variety,
      outcome_internal_variety: outcome_internal_variety,
      outcome_dept_statement_variety: outcome_dept_statement_variety,
      outcome_union_statement_variety: outcome_union_statement_variety,
      abuse_animal: abuse_animal, abuse_restrained: abuse_restrained, urls: urls)
  end


end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  autocomplete :department, :name, full: true, extra_data: [:city, :state, :county, :level, :notes]

  # GET /incidents
  # GET /incidents.json
  def index
    if params[:search_query].present?
      @incidents = Incident.search(params[:search_query]).records
    else
      @incidents = Incident.all
    end
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
  end

  # GET /incidents/new
  def new
    @incident_form = IncidentForm.new
  end

  # GET /incidents/1/edit
  def edit
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident_form = IncidentForm.new incident_form_params

    respond_to do |format|
      if @incident_form.save
        format.html { redirect_to incidents_path, notice: 'Incident was successfully created.' }
      else
        format.html {render :new}
      end
    end
  end

  # PATCH/PUT /incidents/1
  # PATCH/PUT /incidents/1.json
  def update
    respond_to do |format|
      if @incident.update(incident_params)
        format.html { redirect_to @incident, notice: 'Incident was successfully updated.' }
        format.json { render :show, status: :ok, location: @incident }
      else
        format.html { render :edit }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident.destroy
    respond_to do |format|
      format.html { redirect_to incidents_url, notice: 'Incident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident
      @incident = Incident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_form_params
      params.require(:incident_form).permit(:summary, :year, :month, :city, :state,
      :context, :abuse_force, :abuse_search, :abuse_misconduct,
      :abuse_intimidation, :abuse_sexual, :abuse_escalation, :abuse_animal,
      :abuse_restrained,
      {force_variety: []}, {search_variety: []}, {misconduct_variety: []},
      {intimidation_variety: []}, {sexual_variety: []}, {escalation_variety: []},
      :victim_count, :victim_notes, {victim_race: []}, {victim_age: []}, {victim_gender: []},
      :officer_count, {officer_race: []}, {officer_tenure: []}, {officer_gender: []},
      {outcome_physical_variety: []}, {outcome_legal_variety: []},
      {outcome_hr_variety: []},
      {outcome_internal_variety: []}, {outcome_dept_statement_variety: []},
      {outcome_union_statement_variety: []}, :outcome_dollars, :department_name,
      :department_city, :department_state, :department_county, :department_level,
      :department_notes, urls:[])
    end
end

app/helpers/incidents_helper.rb
module IncidentsHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

  def months
    [
      ["January", "01"],
      ["February", "02"],
      ["March", "03"],
      ["April", "04"],
      ["May", "05"],
      ["June", "06"],
      ["July", "07"],
      ["August", "08"],
      ["September", "09"],
      ["October", "10"],
      ["November", "11"],
      ["December", "12"]
    ]
  end

  def context_values
    [
      ["911 Call","911"],
      ["Traffic Stop","traffic-stop"],
      ["Serving Search Warrant","search-warrant"],
      ["Protest","protest"],
      ["Border Crossing","border-crossing"],
      ["Checkpoint","checkpoint"],
      ["Recording Police","recording"],
      ["Chance Encounter","chance"],
      ["In Custody","custody"],
      ["Unknown","unknown"],
      ["Other","other"]
    ]
  end

  def force_variety
    [
      ["Firearm","firearm"],
      ["Taser","taser"],
      ["Chemical","chemical"],
      ["Impact Weapon","impact-weapon"],
      ["Hands/Feet","unarmed"],
      ["Destruction of Property","destruction-property"],
      ["Confiscation of Property","confiscation"],
      ["Use of Dog","dog"],
      ["Other","other"],
      ["Unknown","unknown"]
    ]
  end

  def intimidation_variety
    [
      ["Show of force","show-of-force"],
      ["Threats","threats"],
      ["Verbal Abuse","verbal-abuse"],
      ["Harassing/Stalking","harass-stalk"],
      ["Other","other"],
      ["Unknown","unknown"]
    ]
  end

  def search_variety
    [
      ["Vehicle","vehicle"],
      ["Home","home"],
      ["Person","person"],
      ["Strip","strip"],
      ["Cavity","cavity"],
      ["Other","other"],
      ["Unknown","unknown"]
    ]
  end

  def sexual_variety
    [
      ["Harassment","harassment"],
      ["Abuse of a minor","abuse-minor"],
      ["Abuse of adult","abuse-adult"],
      ["Other","other"],
      ["Unknown","unknown"]
    ]
  end

  def misconduct_variety
    [
      ["Testilying","testilying"],
      ["False report (not in court)","false-report"],
      ["Bribery (Make or accept)","bribe"],
      ["Falsifying /Tampering with Evidence","falsifying-evidence"],
      ["Misuse Data","misuse-data"],
      ["Theft","theft"],
      ["Civil Forfeiture","civil-forfeit"],
      ["False arrest","false-arrest"],
      ["False detainment (no arrest)","false-detainment"],
      ["Other","other"],
      ["Unknown","unknown"]
    ]
  end

  def escalation_variety
    [
      ["Impossible/Conflicting orders","conflicting"],
      ["Invade personal space","invade-space"],
      ["Pain escalation","pain"],
      ["Fail to identify/plain clothes/jumpout","hide-identity"],
      ["False justification","false-justification"]
    ]
  end

  def race_variety
    [
      ["White (European)", "white"],
      ['African-American','black'],
      ['Asian','asian'],
      ['Hispanic/Latino','latino'],
      ['Native American','native-american'],
      ['Other','other'],
      ['Unknown','unknown']
    ]
  end

  def victim_age
    [
      ["Newborn to five years","0-5"],
      ["Six to 12","6-12"],
      ["13 to 17","13-17"],
      ["18 to 24","18-24"],
      ["25 to 34","25-34"],
      ["35 to 44","35-44"],
      ["45 to 54","45-54"],
      ["55 to 64","55-64"],
      ["65 and over","65+"],
      ["Unknown","unknown"]
    ]
  end

  def gender_variety
    [
      ["Male","male"],
      ["Female","female"],
      ["Transgendered","transgendered"],
      ["Unknown","unknown"]
    ]
  end

  def officer_tenure
    [
      ["0 to 4","0-4"],
      ["5 to 9","5-9"],
      ["10 to 14","10-14"],
      ["15 to 19","15-19"],
      ["20 or more","20+"],
      ["Unknown","unknown"]
    ]
  end

  def physical_outcomes
    [
      ["Someone killed (including officer)","killed"],
      ["Someone injured (including officer)", "injured"],
      ["Unknown","unknown"]
    ]
  end

  def legal_outcomes
    [
      ["External Investigation","external-investigation"],
      ["Lawsuit filed","lawsuit"],
      ["Fines/Awards","fines"],
      ["Settlement","settlement"],
      ["Criminal charges","criminal-charges"],
      ["Unrelated Convictions vacated/","vacated"],
      ["Unknown","unknown"]
    ]
  end

  def hr_outcomes
    [
      ["Paid Suspension","paid-suspension"],
      ["Unpaid Suspension","unpaid-suspension"],
      ["Demoted/Reassigned","demoted"],
      ["Fired","fired"],
      ["Quit/Resigned","quit"],
      ["Unknown","unknown"]
    ]
  end

  def internal_outcomes
    [
      ["Cleared","cleared"],
      ["Sanctioned","sanctioned"],
      ["Other","other"],
      ["Unknown","unknown"]
    ]
  end

  def statements
    [
      ["Acted appropriately","acted-appropriately"],
      ["Acted inappropriately","acted-inappropriately"],
      ["Wait and see/benefit of doubt","wait"],
      ["Victim was a criminal","criminal"],
      ["Feared for safety","fear"],
      ["Other","other"],
      ["Unknown","unknown"]
    ]

  end

end

app/views/incidents/_form.html.erb
<%= simple_form_for @incident do |f| %>
  <h2>Basic inforation</h2>
  <%= f.input :summary, label: "Incident summary" %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :year %>
    </div>
    <div class="col-md-6">
      <%= f.input :month, collection: months, prompt: "Select" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= f.input :city %>
    </div>
    <div class="col-md-4">
      <%= f.input :state, collection: us_states, prompt:"Select" %>
    </div>
    <div class="col-md-4">
      <%= f.input :context, collection: context_values, prompt: "Select contex", label:"What lead to the encounter?" %>
    </div>
  </div>

  <h2>Abuse information</h2>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :force_variety, collection: force_variety, input_html: {multiple: true} %>
      <%= f.input :intimidation_variety, collection: intimidation_variety, input_html: {multiple: true} %>
    </div>
    <div class="col-md-4">
      <%= f.input :search_variety, collection: search_variety, input_html: {multiple: true} %>
      <%= f.input :sexual_variety, collection: sexual_variety, input_html: {multiple: true} %>
    </div>
    <div class="col-md-4">
      <%= f.input :misconduct_variety, collection: misconduct_variety, input_html: {multiple: true} %>
      <%= f.input :escalation_variety, collection: escalation_variety, input_html: {multiple: true} %>
    </div>
  </div>
  <%= f.input :abuse_animal, label:"Unreasonable attack on an animal" %>

  <h2>Victim information</h2>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :victim_race, collection: race_variety, input_html: {multiple: true} %>
    </div>
    <div class="col-md-4">
      <%= f.input :victim_age, collection: victim_age, input_html: {multiple: true} %>
    </div>
    <div class="col-md-4">
      <%= f.input :victim_gender, collection: gender_variety, input_html: {multiple: true} %>
    </div>
  </div>
  <%= f.input :victim_notes %>

  <h2>Abuser information</h2>
  <%= f.input :officer_count %>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :officer_race, collection: race_variety, input_html: {multiple: true} %>
    </div>
    <div class="col-md-4">
      <%= f.input :officer_tenure, collection: officer_tenure, input_html: {multiple: true} %>
    </div>
    <div class="col-md-4">
      <%= f.input :officer_gender, collection: gender_variety, input_html: {multiple: true} %>
    </div>
  </div>

  <h2>Outcomes</h2>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :outcome_physical_variety, collection: physical_outcomes, input_html: {multiple: true} %>
      <%= f.input :outcome_internal_variety, collection: internal_outcomes, input_html: {multiple: true} %>
    </div>
    <div class="col-md-4">
      <%= f.input :outcome_legal_variety, collection: legal_outcomes, input_html: {multiple: true} %>
      <%= f.input :outcome_dept_statement_variety, collection: statements, input_html: {multiple: true} %>
    </div>
    <div class="col-md-4">
      <%= f.input :outcome_hr_variety, collection: hr_outcomes, input_html: {multiple: true} %>
      <%= f.input :outcome_union_statement_variety, collection: statements, input_html: {multiple: true} %>
    </div>
  </div>
  <%= f.input :outcome_dollars, label:"Total dollar amount for awards/settlements" %>

  <%= f.submit "Submit incident" %>

<% end %>

app/views/incidents/_newform.html.erb
<%= simple_form_for @incident_form, url: incidents_path do |f| %>
  <h2>Basic inforation</h2>
  <%= f.input :summary, label: "Incident summary" %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :year %>
    </div>
    <div class="col-md-6">
      <%= f.input :month, collection: months, prompt: "Select" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= f.input :city %>
    </div>
    <div class="col-md-4">
      <%= f.input :state, collection: us_states, prompt:"Select" %>
    </div>
    <div class="col-md-4">
      <%= f.input :context, collection: context_values, prompt: "Select contex", label:"What lead to the encounter?" %>
    </div>
  </div>

  <h2>Abuse information</h2>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :force_variety, collection: force_variety, input_html: {multiple: true, size:6 } %>
      <%= f.input :intimidation_variety, collection: intimidation_variety, input_html: {multiple: true, size:6 } %>
    </div>
    <div class="col-md-4">
      <%= f.input :search_variety, collection: search_variety, input_html: {multiple: true, size:6 } %>
      <%= f.input :sexual_variety, collection: sexual_variety, input_html: {multiple: true, size:6 } %>
    </div>
    <div class="col-md-4">
      <%= f.input :misconduct_variety, collection: misconduct_variety, input_html: {multiple: true, size:6 } %>
      <%= f.input :escalation_variety, collection: escalation_variety, input_html: {multiple: true, size:6 } %>
    </div>
  </div>
  <%= f.input :abuse_animal, label:"Unreasonable attack on an animal", as: :boolean %>
  <%= f.input :abuse_restrained, label:"Some abuse targeted at restrained individual", as: :boolean %>

  <h2>Victim information</h2>
  <%= f.input :victim_count %>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :victim_race, collection: race_variety, input_html: {multiple: true, size:6 } %>
    </div>
    <div class="col-md-4">
      <%= f.input :victim_age, collection: victim_age, input_html: {multiple: true, size:6 } %>
    </div>
    <div class="col-md-4">
      <%= f.input :victim_gender, collection: gender_variety, input_html: {multiple: true, size:6 } %>
    </div>
  </div>
  <%= f.input :victim_notes %>

  <h2>Abuser information</h2>
  <%= f.input :officer_count %>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :officer_race, collection: race_variety, input_html: {multiple: true, size:6 } %>
    </div>
    <div class="col-md-4">
      <%= f.input :officer_tenure, collection: officer_tenure, input_html: {multiple: true, size:6 } %>
    </div>
    <div class="col-md-4">
      <%= f.input :officer_gender, collection: gender_variety, input_html: {multiple: true, size:6 } %>
    </div>
  </div>

    <%= f.input :department_name, url: autocomplete_department_name_incidents_path, :as => :autocomplete,
        update_elements: {city: '#incident_form_department_city',
                          state: '#incident_form_department_state',
                          county: '#incident_form_department_county',
                          level: '#incident_form_department_level'},
        input_html: {class:"form-control"} %>
  <div class="row">
    <div class="col-md-3">
      <%= f.input :department_city %>
    </div>
    <div class="col-md-3">
      <%= f.input :department_state, collection: us_states, prompt:"Select" %>
    </div>
    <div class="col-md-3">
      <%= f.input :department_county %>
    </div>
    <div class="col-md-3">
      <%= f.input :department_level, collection: department_levels, prompt:"Select" %>
    </div>
  </div>
  <%= f.input :department_notes %>


  <h2>Outcomes</h2>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :outcome_physical_variety, collection: physical_outcomes, input_html: {multiple: true, size:6 } %>
      <%= f.input :outcome_internal_variety, collection: internal_outcomes, input_html: {multiple: true, size:6 } %>
    </div>
    <div class="col-md-4">
      <%= f.input :outcome_legal_variety, collection: legal_outcomes, input_html: {multiple: true, size:6 } %>
      <%= f.input :outcome_dept_statement_variety, collection: statements, input_html: {multiple: true, size:6 } %>
    </div>
    <div class="col-md-4">
      <%= f.input :outcome_hr_variety, collection: hr_outcomes, input_html: {multiple: true, size:6 } %>
      <%= f.input :outcome_union_statement_variety, collection: statements, input_html: {multiple: true, size:6 } %>
    </div>
  </div>
  <%= f.input :outcome_dollars, label:"Total dollar amount for awards/settlements" %>

  <h2>Sources</h2>
  <div ng-app="addUrls">
    <div ng-controller="urlController">
      <div class="form-group" ng-repeat="url in urls">
        <label for="url" ng-show="showUrlLabel(url)" class="control-label">Urls</label>
        <input type="text" ng-model="url.value" name="incident_form[urls][]" id="incident_form_url" placeholder="Enter a url" class="form-control">
        <button type="button" ng-show="showAddUrl(url)" ng-click="addNewUrl()">Add another URL</button>

      </div>
    </div>
  </div>

  <%= f.submit "Submit incident" %>

<% end %>

app/views/incidents/edit.html.erb
<h1>Editing Incident</h1>

<%= render 'form' %>

<%= link_to 'Show', @incident %> |
<%= link_to 'Back', incidents_path %>

app/views/incidents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Incidents</h1>

<%= render '/layouts/search' %>

<p><strong><%= @incidents.count %></strong> <%= "incident".pluralize(@incidents.count) %> and counting.</p>


<%= link_to 'New Incident', new_incident_path %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Summary</th>
      <th>Department</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @incidents.each do |incident| %>
      <tr>
        <td><%= link_to incident.summary, incident %></td>
        <td><%= link_to incident.department.name, department_path(incident.department) %></td>
        <td><%= link_to 'Edit', edit_incident_path(incident) %>
            <%= link_to 'Destroy', incident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Incident', new_incident_path %>

app/views/incidents/new.html.erb
<h1>New Incident</h1>

<%= render 'newform' %>

<%= link_to 'Back', incidents_path %>

app/views/incidents/show.html.erb
<p id="notice"><%= notice %></p>
<%= show_for @incident do |i| %>
  <h2>Basic inforation</h2>
  <%= i.attribute :summary %>
  <div class="row">
    <div class="col-md-6">
      <%= i.attribute :year %>
    </div>
    <div class="col-md-6">
      <%= i.attribute :month %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= i.attribute :city %>
    </div>
    <div class="col-md-4">
      <%= i.attribute :state %>
    </div>
    <div class="col-md-4">
      <%= i.attribute :context %>
    </div>
  </div>
<% end %>